{"is_source_file": false, "format": "", "description": "", "external_files": [], "external_methods": [], "published": [], "classes": [], "methods": [], "calls": [], "search-terms": ["gradle", "buildscript", "repositories", "dependencies", "com.android.tools.build:gradle"], "state": 2, "file_id": 16, "knowledge_revision": 42, "git_revision": "", "hash": "e2bdb13287a29af1b9fd036dc9649d37", "format-version": 4, "code-base-name": "default", "filename": "colorflip/build.gradle", "revision_history": [{"42": ""}]}